name: Process Snake Move

on:
  issues:
    types: [opened]

jobs:
  process-move:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permite escribir en el repositorio
      issues: write    # Permite cerrar issues
    steps:
      # Paso 0: Instalar dependencias (jq)
      - name: Install dependencies
        run: |
          sudo apt-get install -y jq

      # Paso 1: Obtener el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Paso 3: Obtener el cuerpo del issue (movimiento)
      - name: Get issue body
        id: issue
        run: |
          echo "MOVE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
          | jq -r '.body')" >> $GITHUB_ENV

      # Paso 4: Ejecutar el script para actualizar el estado del juego
      - name: Update game state
        run: |
          python update_game.py "$MOVE"

      # Paso 5: Ejecutar el script para actualizar el README.md
      - name: Update README.md
        run: |
          python update_readme.py

      # Paso 6: Subir los cambios al repositorio
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add game_state.json game_board.txt README.md
          git commit -m "Update game state with move: $MOVE"
          git push

      # Paso 7: Cerrar el issue
      - name: Close issue
        run: |
          curl -s -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
          -d '{"body": "✅ Movimiento procesado. ¡Gracias por jugar!"}'

          curl -s -X PATCH \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
          -d '{"state": "closed"}'
